project:
  type: website
  resources: 
    - "notes/*"

website:
  title: "Linear Algebra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - notes.qmd
      - homework.qmd
      - exams.qmd

format:
  html:    
    theme:
      light: cosmo
    toc: true



