project:
  type: website
  resources: 
    - "notes/*"

website:
  title: "Linear Algebra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - notes.qmd

format:
  html:    
    theme:
      light: cosmo
      # dark: [cosmo, theme-dark.scss]
    toc: true



